[package]
edition = "2021"
name = "exon-examples"
version = "0.3.4-beta.10"

[dependencies]
arrow = {workspace = true}
datafusion = {workspace = true}
exon = {path = "../exon/exon-core", features = ["all"]}
tokio = {version = "1", features = ["io-util"]}
