[package]
edition = '2021'
name = 'exonr'
version = '0.1.0'

[lib]
crate-type = ['staticlib']
name = 'exonr'

[dependencies]
arrow = {version = "49.0.0", features = ["ffi"]}
datafusion = "34"
exon = {version = "0.6.0", features = ["all"]}
extendr-api = '*'
tokio = {version = '1', features = ['rt']}
url = "2.4.0"

[workspace]
