[package]
edition = '2021'
name = 'exonr'
version = '0.1.0'

[lib]
crate-type = ['staticlib']
name = 'exonr'

[dependencies]
arrow = {version = "48.0.1", features = ["ffi"]}
datafusion = "33"
exon = {version = "0.4.2", features = ["all"]}
extendr-api = '*'
tokio = {version = '1', features = ['rt']}
url = "2.4.0"

[workspace]
